import type {Metadata} from 'next';

import Navbar from '~/components/molecules/LayoutComponents/Navbar';
import '~/styles/globals.css';
import {cn} from '~/lib/utils';
import {generalSans} from '~/fonts/generalSans';
import Providers from '~/components/providers';
import {Toaster} from '~/components/ui/toaster';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased pt-16',
          generalSans.className,
        )}
      >
        <Providers>
          <Navbar />
          {children}
          {modal}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
