import type {Metadata} from 'next';
import {Inter as FontSans} from 'next/font/google';
import Navbar from '~/components/molecules/LayoutComponents/Navbar';
import '~/styles/globals.css';
import {cn} from '~/lib/utils';
import {generalSans} from '~/fonts/generalSans';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    'min-h-screen bg-background font-sans antialiased pt-16',
                    generalSans.className,
                )}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
